# Generated by Django 3.1.1 on 2023-09-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0002_cheese_country_of_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='country_of_origin',
            field=models.CharField(max_length=255, verbose_name='Country of Origin'),
        ),
    ]
